config/routes.rb
Rails.application.routes.draw do
  root "links#index"

  resources :screenshots
  resources :links

  post "selenium_monitor", to: "selenium_monitor#create", as: "init_monitor"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, :presence => true, :url => true
end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  def index
    @links = Link.all
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)

    @link.url = "https://" + @link.url unless @link.url.include?("https://")

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    screenshots_link = Screenshot.where(link_id: @link.id)
    screenshots_link.delete_all

    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:url)
    end
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: %i[ show destroy]

  def index
    @screenshots = Screenshot.all.order("created_at DESC")
  end

  # GET /screenshots/1 or /screenshots/1.json
  def show
  end
  
  # DELETE /screenshots/1 or /screenshots/1.json
  def destroy
    @screenshot.destroy

    respond_to do |format|
      format.html { redirect_to screenshots_url, notice: "Screenshot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screenshot
      @screenshot = Screenshot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screenshot_params
      params.require(:screenshot).permit(:title, :image, :link_id)
    end
end

app/controllers/selenium_monitor_controller.rb
class SeleniumMonitorController < ApplicationController
  require 'selenium-webdriver'

  def create
    Link.all.each do |link|
      date = DateTime.now
    
      @driver = Selenium::WebDriver.for :chrome
      wait = Selenium::WebDriver::Wait.new(:timeout => 10)
      @driver.get link.url
    
      path = "./app/assets/images/#{link.id}#{date}.png"
    
      @driver.save_screenshot(path)
      @driver.quit
    
      image = File.new(path, "r")
    
      s = Screenshot.new
      s.link_id = link.id
      s.image = image
      s.title = link.url
      s.save!
    
      image.close
    
      File.delete(path) if File.exist?(path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonitorLinks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.url %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to new_link_path, method: :get, class:'button' do %>
    New Link
  <% end %>
<%= button_to init_monitor_path, method: :post, class:'button' do %>
    Init Monitor
  <% end %>
<%= button_to screenshots_path, method: :get, class:'button' do %>
    Screenshots
  <% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/screenshots/_form.html.erb
<%= form_with(model: screenshot) do |form| %>
  <% if screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
        <% screenshot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.text_field :link_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/screenshots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Screenshots</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Image</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screenshots.each do |screenshot| %>
      <tr>
        <td><%= screenshot.title %></td>
        <td><%= image_tag screenshot.image_url if screenshot.image %></td>
        <td><%= screenshot.created_at %></td>
        <td><%= link_to 'Show', screenshot %></td>
        <td><%= link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', links_path %>

app/views/screenshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @screenshot.image_url if @screenshot.image %>
</p>

<%= link_to 'Back', screenshots_path %>